{
 "title": "ARM 3",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Вимір",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "БД3",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Камера Відеоспостереження", "gridPos": { "h": 16, "w": 16, "x": 4, "y": 0 } },
  {
   "title": "БД4",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Вимір",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Фон",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state_amount_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Фон",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state_amount_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Вимір",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "БД1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "БД2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Вимір",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Фон",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state_amount_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Фон",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state_amount_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Одиниці вим.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lamda\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Немає зв'язку з центральним офісом Екоцентр",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 16 },
   "options": {
    "content": "\n<a href=\"http://192.168.0.38:8080/\" class=\"button\" target=\"_blank\" style=\"display: inline-block; padding: 10px 20px; font-size: 16px; cursor: pointer; text-align: center; text-decoration: none; outline: none; color: #fff; background-color: #f51271; border: none; border-radius: 15px; box-shadow: 0 9px #999;\">Натисніть при відсутності зв'язку</a>\n"
   }
  },
  {
   "title": "Стан Радіометра",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"radio_state\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Зупинка звукової тривоги",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 16 },
   "options": {
    "content": "<a href=\"http://192.168.0.38:8000/stop\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"display: inline-block; padding: 10px 60px; font-size: 15px; cursor: pointer; text-align: center; text-decoration: none; outline: none; color: #fff; background-color: #ff0000; border: none; border-radius: 10px; box-shadow: 0 10px #999;\">STOP</a>\r\n"
   }
  },
  {
   "title": "Внесення ручних вимірів",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 16 },
   "options": {
    "content": "<a href=\"http://192.168.0.23:5000/\" target=\"_blank\" style=\"display: inline-block; padding: 10px 20px; font-size: 16px; cursor: pointer; text-align: center; text-decoration: none; outline: none; color: #fff; background-color: #800080; border: none; border-radius: 15px; box-shadow: 0 9px #999;\">Внесіть виміри</a>\n"
   }
  },
  {
   "title": "Одиниці вим.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lamda\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}