{
 "title": "ARM 3",
 "time": { "from": "2024-06-09T21:00:00.000Z", "to": "2024-06-12T20:59:59.000Z" },
 "panels": [
  {
   "title": "Поточне значення №1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Стан Датчика №1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Камера Відеоспостереження", "gridPos": { "h": 6, "w": 10, "x": 7, "y": 0 } },
  {
   "title": "Стан Датчика №3",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Поточне значення №3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Стале значення фону №1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state_amount_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Стале значення фону №3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state_amount_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Статус Радіометра",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rad_status\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Поточне значення №2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Стан Датчика №2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Стан Датчика №4",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Поточне значення №4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Зупинка звукової тривоги",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 10 },
   "options": {
    "content": "<a href=\"http://192.168.0.58:5001/stop\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"display: inline-block; padding: 8px 16px; font-size: 14px; cursor: pointer; text-align: center; text-decoration: none; outline: none; color: #fff; background-color: #ff0000; border: none; border-radius: 10px; box-shadow: 0 6px #999;\">STOP</a>\r\n<a href=\"http://192.168.0.58:5002/stop\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"display: inline-block; padding: 8px 16px; font-size: 14px; cursor: pointer; text-align: center; text-decoration: none; outline: none; color: #000; background-color: #ffff00; border: none; border-radius: 10px; box-shadow: 0 6px #999;\">STOP</a>\r\n"
   }
  },
  {
   "title": "Внесення ручних вимірів",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 10 },
   "options": {
    "content": "<a href=\"http://192.168.0.23:8000/\" target=\"_blank\" style=\"display: inline-block; padding: 10px 20px; font-size: 16px; cursor: pointer; text-align: center; text-decoration: none; outline: none; color: #fff; background-color: #800080; border: none; border-radius: 15px; box-shadow: 0 9px #999;\">Внесіть виміри</a>\n"
   }
  },
  {
   "title": "Стале значення фону №2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state_amount_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Стале значення фону №4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state_amount_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Немає зв'язку з центральним офісом Екоцентр",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 13 },
   "options": {
    "content": "\n<a href=\"http://192.168.0.58:5000/\" class=\"button\" target=\"_blank\" style=\"display: inline-block; padding: 10px 20px; font-size: 16px; cursor: pointer; text-align: center; text-decoration: none; outline: none; color: #fff; background-color: #f51271; border: none; border-radius: 15px; box-shadow: 0 9px #999;\">Натисніть при відсутності зв'язку</a>\n"
   }
  }
 ]
}