{
 "title": "Graficks",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Дитятки №1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_1\" or r[\"_field\"] == \"state_amount_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Дитятки №2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_2\" or r[\"_field\"] == \"state_amount_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Дитятки №3",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_3\" or r[\"_field\"] == \"state_amount_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Дитятки №4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_4\" or r[\"_field\"] == \"state_amount_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Паришів №1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_1\" or r[\"_field\"] == \"state_amount_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Паришів №2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_2\" or r[\"_field\"] == \"state_amount_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Паришів №3",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_3\" or r[\"_field\"] == \"state_amount_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Паришів №4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_4\" or r[\"_field\"] == \"state_amount_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Діброва №1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_1\" or r[\"_field\"] == \"state_amount_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Діброва №2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_2\" or r[\"_field\"] == \"state_amount_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Діброва №3",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_3\" or r[\"_field\"] == \"state_amount_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Діброва №4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_4\" or r[\"_field\"] == \"state_amount_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Лелів №1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_1\" or r[\"_field\"] == \"state_amount_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Лелів №2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_2\" or r[\"_field\"] == \"state_amount_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Лелів №3",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_3\" or r[\"_field\"] == \"state_amount_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Лелів №4",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amount_4\" or r[\"_field\"] == \"state_amount_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3\" or r[\"host\"] == \"host3_e\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}