{
 "title": "Админ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Дит_1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Дит_2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Дит_3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Дит_4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Діб_1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Діб_2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Діб_3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Діб_4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Камера Відеоспостереження", "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 } },
  { "title": "Камера Відеоспостереження", "gridPos": { "h": 7, "w": 8, "x": 14, "y": 4 } },
  {
   "title": "Лел_1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Лел_2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Лел_3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Лел_4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Пар_1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_1\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Пар_2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Пар_3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_3\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Пар_4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Graf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"triger_state_4\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host3_e\" or r[\"host\"] == \"host3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Камера Відеоспостереження", "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 } },
  { "title": "Камера Відеоспостереження", "gridPos": { "h": 7, "w": 8, "x": 14, "y": 15 } }
 ]
}